<a href="https://colab.research.google.com/github/Jpablo179804/MineriaDatos/blob/main/MineriaDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria De Datos


##Primer Parcial




###Introduccion


####Conceptos

####Ciencia de Datos

#####Help and Documentation in IPython

In [57]:
#La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [58]:
#Otra forma de obtener ayuda es con ?
len?

In [59]:
#ejemplo de ayuida de una lista
L = [1, 2, 3]
L.insert?

In [60]:
#Ejemplo de ayuda
L?

In [61]:
#ejemplo de funcion con docString
def square(a):
  """Return the square of a."""
  return a ** 2


In [62]:

square?

In [63]:
#ejemplo de ayuda de funcion personalizada
square??

In [64]:
#Ejemplo de funcion built.in
len??

#####IPython Magic Commands

In [65]:
#para evaluar el desempeño en base al tiempo
%timeit L = [n ** 2 for n in range(1000)]

40.6 µs ± 835 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [66]:
#con doble %% podemos evakluar el desmpeño en cuanto al tiempo; en mas de una linea de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)


52.9 µs ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#####IPython and Shell Commands

In [67]:
#si se pone ! se ejecuta en una subseccion
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [68]:
!pws

/bin/bash: line 1: pws: command not found


In [69]:
!echo "printing from the shell"

printing from the shell


In [70]:
#guardar lo del directorio
contents = !ls

In [71]:
#imprimir lo anterior
print(contents)

['anscombe.json\t\t      mnist_test.csv', 'california_housing_test.csv   mnist_train_small.csv', 'california_housing_train.csv  README.md']


In [72]:
directory = !pwd

In [73]:
#imprimir lo anterior
print(directory)

['/content/sample_data']


In [74]:
type(directory)

IPython.utils.text.SList

In [75]:
message = "hello from Python"

In [76]:
!echo {message}

hello from Python


In [77]:
%cd /content/

/content


In [78]:
%ls

sample_data/


In [79]:
%cd sample_data/

/content/sample_data


In [80]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [81]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'd4ae5b87e691',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

#####Understanding Data Types in Python

In [82]:
#importa numpy y renombralo como np
#libreria para arreglos de n dimenciones
import numpy as np

In [83]:
#arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [84]:
#arreglo donde hace un cast a flotante
#el primer dato es float
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [85]:
#cast del array a float
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [86]:
#cast del array a entero
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [87]:
#cuando el argumento de np.array es una iteracion anidada, genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

######Creating Arrays from Scratch

In [88]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [91]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
#comienza en 0, llega hasta antes de 20 y se incrementa de dos en dos
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [92]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [93]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [94]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
#.normal(media, desviacion estandar, (matriz de x, x))
np.random.normal(0, 1, (3, 3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [95]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

In [96]:
# Create a 3x3 identity matrix
#cuando la diagonal principal tiene puros 1´s
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

#####The Basics of NumPy Arrays

######NumPy Array Attributes

In [98]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [99]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [100]:
print("dtype:", x3.dtype)

dtype: int64


In [101]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


######Array Indexing: Accessing Single Elements

In [102]:
x1

array([5, 0, 3, 3, 7, 9])

In [103]:
x1[0]

np.int64(5)

In [104]:
x1[4]

np.int64(7)

In [105]:
x1[-1]

np.int64(9)

In [106]:
x1[-2]

np.int64(7)

In [107]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [108]:
x2[0, 0]

np.int64(3)

In [109]:
x2[2, 0]

np.int64(1)

In [110]:
x2[2, -1]

np.int64(7)

In [111]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

####Análisis Estadístico Básico con NumPy

#####Medidas Estadísticas Básicas

######Media (Mean)

In [112]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


######Promedio (Average) y Promedio Ponderado

In [113]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

######Mediana

In [114]:
mediana = np.median(data)

######Varianza y Desviación Estándar

In [115]:
varianza = np.var(data)
desviacion = np.std(data)

#####Generación de Datos Aleatorios

In [116]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


#####Correlación

In [117]:
corr = np.corrcoef([1,2,3], [1,5,7])