<a href="https://colab.research.google.com/github/Jpablo179804/MineriaDatos/blob/main/MineriaDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria De Datos


##Primer Parcial




###Introduccion


####Conceptos

####Ciencia de Datos

#####Help and Documentation in IPython

In [1]:
#La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
#Otra forma de obtener ayuda es con ?
len?

In [3]:
#ejemplo de ayuida de una lista
L = [1, 2, 3]
L.insert?

In [4]:
#Ejemplo de ayuda
L?

In [5]:
#ejemplo de funcion con docString
def square(a):
  """Return the square of a."""
  return a ** 2


In [6]:

square?

In [7]:
#ejemplo de ayuda de funcion personalizada
square??

In [8]:
#Ejemplo de funcion built.in
len??

#####IPython Magic Commands

In [9]:
#para evaluar el desempeño en base al tiempo
%timeit L = [n ** 2 for n in range(1000)]

245 µs ± 76.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
#con doble %% podemos evakluar el desmpeño en cuanto al tiempo; en mas de una linea de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)


The slowest run took 4.78 times longer than the fastest. This could mean that an intermediate result is being cached.
179 µs ± 105 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#####IPython and Shell Commands

In [11]:
#si se pone ! se ejecuta en una subseccion
!ls

sample_data


In [12]:
!pws

/bin/bash: line 1: pws: command not found


In [13]:
!echo "printing from the shell"

printing from the shell


In [14]:
#guardar lo del directorio
contents = !ls

In [15]:
#imprimir lo anterior
print(contents)

['sample_data']


In [16]:
directory = !pwd

In [17]:
#imprimir lo anterior
print(directory)

['/content']


In [18]:
type(directory)

IPython.utils.text.SList

In [19]:
message = "hello from Python"

In [20]:
!echo {message}

hello from Python


In [21]:
%cd /content/

/content


In [22]:
%ls

sample_data/


In [23]:
%cd sample_data/

/content/sample_data


In [24]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [25]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '46348a5009c1',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

#####Understanding Data Types in Python

In [26]:
#importa numpy y renombralo como np
#libreria para arreglos de n dimenciones
import numpy as np

In [27]:
#arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [28]:
#arreglo donde hace un cast a flotante
#el primer dato es float
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [29]:
#cast del array a float
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [30]:
#cast del array a entero
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [31]:
#cuando el argumento de np.array es una iteracion anidada, genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

######Creating Arrays from Scratch

In [32]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [35]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
#comienza en 0, llega hasta antes de 20 y se incrementa de dos en dos
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.05242945, 0.15238339, 0.70384409],
       [0.40187846, 0.81434208, 0.62962878],
       [0.18922233, 0.76537458, 0.19561625]])

In [38]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
#.normal(media, desviacion estandar, (matriz de x, x))
np.random.normal(0, 1, (3, 3))

array([[ 0.27511303,  0.58341248,  0.45809358],
       [-0.93316582, -0.91593018,  0.64583384],
       [-0.01706793, -1.34010901,  1.12708138]])

In [39]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 2, 9],
       [7, 7, 7],
       [1, 7, 0]])

In [40]:
# Create a 3x3 identity matrix
#cuando la diagonal principal tiene puros 1´s
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

#####The Basics of NumPy Arrays

######NumPy Array Attributes

In [42]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [43]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [44]:
print("dtype:", x3.dtype)

dtype: int64


In [45]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


######Array Indexing: Accessing Single Elements

In [46]:
x1

array([5, 0, 3, 3, 7, 9])

In [47]:
x1[0]

np.int64(5)

In [48]:
x1[4]

np.int64(7)

In [49]:
x1[-1]

np.int64(9)

In [50]:
x1[-2]

np.int64(7)

In [51]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [52]:
x2[0, 0]

np.int64(3)

In [53]:
x2[2, 0]

np.int64(1)

In [54]:
x2[2, -1]

np.int64(7)

In [55]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

####Análisis Estadístico Básico con NumPy

#####Medidas Estadísticas Básicas

######Media (Mean)

In [56]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


######Promedio (Average) y Promedio Ponderado

In [57]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

######Mediana

In [58]:
mediana = np.median(data)

######Varianza y Desviación Estándar

In [59]:
varianza = np.var(data)
desviacion = np.std(data)

#####Generación de Datos Aleatorios

In [60]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


#####Correlación

In [61]:
corr = np.corrcoef([1,2,3], [1,5,7])

####01 Cuadros estadísticos


In [62]:

import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),
}

# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

({'n': 60,
  'min': 20.0,
  'p25': 21.0,
  'mediana': 22.0,
  'media': 22.3,
  'p75': 23.0,
  'max': 26.0,
  'rango(ptp)': 6.0,
  'var_muestral': 1.8406779661016948,
  'std_muestral': 1.3567158752302173,
  'cv': 0.06083927691615324},
 {'Si': 54, 'No': 6},
 {'Si': 18, 'No': 42},
 {'Si': 52, 'No': 8},
 array([[ 6,  0],
        [36, 18]]),
 array([[ 1,  5],
        [ 7, 47]]),
 array([[ 5, 37],
        [ 3, 15]]),
 {'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
  'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
  'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}})

In [66]:
df.head(3)

,Marca temporal,Número de matrícula,¿Cuántos años cumplidos tienes?,¿Has realizado programas utilizando Python?,¿Has utilizado Google Colab?,¿Tienes cuenta de GitHub?,edad,prog_python,usa_colab,cuenta_github
0,19/01/2026 18:32:18,178920,22,Si,No,Si,22,True,False,True
1,19/01/2026 18:32:23,182712,21,Si,No,Si,21,True,False,True
2,19/01/2026 18:32:25,180370,26,Si,Si,Si,26,True,True,True


In [73]:
print(f'ndarray edad: {edad}') #muestra todo el array
print(f'ndarray edad primeros 5 elemnts: {edad[:5]}') #solo los primeros 5
print(f'ndarray prog_py primeros 5 elemnts: {prog_py[:5]}')
print(f'ndarray usa_colab primeros 5 elemnts: {usa_colab[:5]}')
print(f'ndarray cuenta_gh primeros 5 elemnts: {cuenta_gh[-5:]}') #solo los ultimos 5

ndarray edad: [22. 21. 26. 21. 24. 22. 22. 21. 23. 22. 23. 22. 23. 22. 22. 22. 22. 22.
 21. 24. 21. 23. 24. 21. 22. 22. 24. 21. 23. 20. 22. 21. 22. 20. 24. 24.
 21. 25. 23. 23. 23. 21. 23. 23. 22. 24. 22. 22. 22. 26. 20. 22. 21. 21.
 22. 25. 21. 22. 22. 21.]
ndarray edad primeros 5 elemnts: [22. 21. 26. 21. 24.]
ndarray prog_py primeros 5 elemnts: [ True  True  True  True  True]
ndarray usa_colab primeros 5 elemnts: [False False  True  True False]
ndarray cuenta_gh primeros 5 elemnts: [ True  True  True  True  True]


In [74]:
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [76]:
print(f'La frecuencia de utilizar python: {freq_python}')
print(f'La frecuencia de utilizar colab: {freq_colab}')
print(f'La frecuencia de utilizar github: {freq_gh}')

La frecuencia de utilizar python: {'Si': 54, 'No': 6}
La frecuencia de utilizar colab: {'Si': 18, 'No': 42}
La frecuencia de utilizar github: {'Si': 52, 'No': 8}


In [79]:
print(f'Tabla python vs colab \n {tab_py_colab}')
print(f'Tabla python vs github \n {tab_py_gh}')
print(f'Tabla colab vs github \n {tab_colab_gh}')

Tabla python vs colab 
 [[ 6  0]
 [36 18]]
Tabla python vs github 
 [[ 1  5]
 [ 7 47]]
Tabla colab vs github 
 [[ 5 37]
 [ 3 15]]
