<a href="https://colab.research.google.com/github/Jpablo179804/MineriaDatos/blob/main/MineriaDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria De Datos


##Primer Parcial




###Introduccion


####Conceptos

####Ciencia de Datos

#####Help and Documentation in IPython

In [160]:
#La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [161]:
#Otra forma de obtener ayuda es con ?
len?

In [162]:
#ejemplo de ayuida de una lista
L = [1, 2, 3]
L.insert?

In [163]:
#Ejemplo de ayuda
L?

In [164]:
#ejemplo de funcion con docString
def square(a):
  """Return the square of a."""
  return a ** 2


In [165]:

square?

In [166]:
#ejemplo de ayuda de funcion personalizada
square??

In [167]:
#Ejemplo de funcion built.in
len??

#####IPython Magic Commands

In [168]:
#para evaluar el desempeño en base al tiempo
%timeit L = [n ** 2 for n in range(1000)]

39.6 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [169]:
#con doble %% podemos evakluar el desmpeño en cuanto al tiempo; en mas de una linea de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)


51.1 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#####IPython and Shell Commands

In [170]:
#si se pone ! se ejecuta en una subseccion
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [171]:
!pws

/bin/bash: line 1: pws: command not found


In [172]:
!echo "printing from the shell"

printing from the shell


In [173]:
#guardar lo del directorio
contents = !ls

In [174]:
#imprimir lo anterior
print(contents)

['anscombe.json\t\t      mnist_test.csv', 'california_housing_test.csv   mnist_train_small.csv', 'california_housing_train.csv  README.md']


In [175]:
directory = !pwd

In [176]:
#imprimir lo anterior
print(directory)

['/content/sample_data']


In [177]:
type(directory)

IPython.utils.text.SList

In [178]:
message = "hello from Python"

In [179]:
!echo {message}

hello from Python


In [180]:
%cd /content/

/content


In [181]:
%ls

sample_data/


In [182]:
%cd sample_data/

/content/sample_data


In [183]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [184]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '85e77182117b',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

#####Understanding Data Types in Python

In [185]:
#importa numpy y renombralo como np
#libreria para arreglos de n dimenciones
import numpy as np

In [186]:
#arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [187]:
#arreglo donde hace un cast a flotante
#el primer dato es float
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [188]:
#cast del array a float
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [189]:
#cast del array a entero
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [190]:
#cuando el argumento de np.array es una iteracion anidada, genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])